# Site settings
title: 라라벨 한국어 매뉴얼
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/jekyll-test/" # the subpath of your site, e.g. /blog/
url: "http://www.xpressengine.com" # the base hostname & protocol for your site
github_username:  xpressengine

# markdown settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "no_highlighter", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

# Build settings
permalink: "/docs/:categories/:title"
excerpt_separator: ""